"""permite_nombres_repetidos_y_cambia_fk_ventas

Revision ID: 244a98aed6b6
Revises: f95ce531b748
Create Date: 2026-05-05 15:31:00.760413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244a98aed6b6'
down_revision: Union[str, Sequence[str], None] = 'f95ce531b748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ventas_producto_fkey'), 'ventas', type_='foreignkey')
    op.drop_constraint(op.f('productos_nombre_key'), 'productos', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('productos_nombre_key'), 'productos', ['nombre'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('ventas_producto_fkey'), 'ventas', 'productos', ['producto'], ['nombre'])
    # ### end Alembic commands ###
